/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiSpellRouteImport } from './routes/api/spell'

const ApiSpellRoute = ApiSpellRouteImport.update({
  id: '/api/spell',
  path: '/api/spell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/spell': typeof ApiSpellRoute
}
export interface FileRoutesByTo {
  '/api/spell': typeof ApiSpellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/spell': typeof ApiSpellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/spell'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/spell'
  id: '__root__' | '/api/spell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiSpellRoute: typeof ApiSpellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/spell': {
      id: '/api/spell'
      path: '/api/spell'
      fullPath: '/api/spell'
      preLoaderRoute: typeof ApiSpellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiSpellRoute: ApiSpellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
